services:
  postgres-prod:
    image: postgres:15
    container_name: postgres-prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - production
    deploy:
      resources:
        limits:
          memory: 150M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-prod:
    image: redis:7-alpine
    container_name: redis-prod
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis_data:/data
    networks:
      - production
    deploy:
      resources:
        limits:
          memory: 64M
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n-prod:
    build: .
    # image: n8nio/n8n:latest
    container_name: n8n-prod
    restart: always
    environment:
      N8N_CORS_ORIGIN: http://localhost:3000,https://axiamasi.com
      EXECUTIONS_DATA_PRUNE: true
      EXECUTIONS_DATA_PRUNE_MAX_COUNT: 200
      N8N_LOG_LEVEL: error
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres-prod
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      N8N_REDIS_HOST: redis-prod
      N8N_REDIS_PORT: 6379
      N8N_REDIS_PASSWORD: ${REDIS_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      N8N_HOST: ${DOMAIN_NAME:-localhost}
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://${DOMAIN_NAME:-localhost}
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_TRUSTED_PROXIES: ${N8N_TRUSTED_PROXIES}
      N8N_CONCURRENCY_PRODUCTION_LIMIT: 2
      NODE_OPTIONS: --max-old-space-size=512
      N8N_PROXY_HOPS: 1
      NODE_ENV: production
      N8N_BLOCK_FS_WRITE_ACCESS: "false"
      N8N_RESTRICT_FILE_ACCESS_TO: "/root/.n8n-files;/tmp/clipper;/data/output"
      NODES_EXCLUDE: "[]"
      N8N_TRUST_PROXY: "true"
      EXECUTIONS_DATA_MAX_AGE: 168
    volumes:
      - ./n8n_data:/root/.n8n
      - ./scripts:/app/scripts
      - /opt/n8n-clipper/output:/data/output
      - /opt/n8n-clipper/tmp:/tmp/clipper
      - /opt/n8n-clipper/cookies:/cookies
    user: "root"
    ports:
      - "5679:5678"
    depends_on:
      postgres-prod:
        condition: service_healthy
      redis-prod:
        condition: service_healthy
    networks:
      - production
    deploy:
      resources:
        limits:
          memory: 1G

  gowa:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    container_name: gowa-prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - APP_BASIC_AUTH=${GOWA_BASIC_AUTH:-admin:@Agusahmad17}
      - APP_PORT=3000
      - APP_DEBUG=false
      - APP_OS=Mac OS
      - WHATSAPP_WEBHOOK=${WHATSAPP_WEBHOOK}
      - TZ=Asia/Jakarta
    volumes:
      - ./gowa_data:/app/storages
      - ./statics:/app/statics
    networks:
      - production
    deploy:
      resources:
        limits:
          memory: 150M

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --protocol http2
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN_PROD}
    networks:
      - production # Pake satu network aja
    deploy:
      resources:
        limits:
          memory: 64M

networks:
  production:
    driver: bridge
